version: "3.8"
services: 
    db:
        container_name: my_pictures_db
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: my_pictures
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    backend:
        container_name: my_pictures_backend
        build: ./backend
        environment: 
            - NODE_ENV=PROD
        depends_on: 
            - db
        ports:
            - "3333:3333"
    frontend:
        container_name: my_pictures_frontend
        build: ./my-pictures
        depends_on: 
            - db
            - backend
        ports:
            - "3000:3000"
volumes:
    pgdata:
